### ISSUE TITLE
Nanosaur: Assertion Failed!

### ISSUE THREAD

**Issue by davidalanroth** [jorio/MightyMike#10]
Error message while playing Mighty Mike Version 3.0.0 (Created: Sunday, April 11,2021 at 6:17 PM) while on this level for about 5 minutes:

Nanosaur: Assertion Failed!
tileAttribs
DoEnemyCollisionDetect: 206

This is on a Mac Mini (2018), 3.2 Ghz 6-Core Intel Core i7, Memory 64 GB
macOS Catalina, version 10.15.7 (19H15)

I'd be glad to provide any additional information requested to assistant in trouble-shooting this, such as Console logs, etc.

![Screen Shot 2022-02-21 at 11 56 00 PM](https://user-images.githubusercontent.com/294931/155066798-bd434162-dc39-4167-954e-10167898684c.png)

**Comment by jorio** [comment]
@davidalanroth, this should be fixed in [Mighty Mike 3.0.1](https://github.com/jorio/MightyMike/releases/tag/v3.0.1)!
