### ISSUE TITLE
[SOLVED] Logitech f310 not recognized.

### ISSUE THREAD

**Issue by ghost** [jorio/MightyMike#11]
Running Linux Mint 20.3.
Mighty Mike 3.0.0 from FlatHub
Logitech f310 gamepad works in other games, but not recognized in this game.

**Comment by jorio** [comment]
Can you try [Mighty Mike 3.0.1](https://github.com/jorio/MightyMike/releases/tag/v3.0.1)? The flatpak is out of date.

**Comment by ghost** [comment]
I will, it may take a little bit. New to linux, so still having to do web searches to figure a lot of this out.

**Comment by ghost** [comment]
Found the AppImage for 3.0.1, that works.  Thank you very much for the help.
