### ISSUE TITLE
Possible to double window size when not in fullscreen mode?

### ISSUE THREAD

**Issue by eisnerguy1** [jorio/MightyMike#2]
Everything about the new version is amazing. I did have 1 suggestion though: is it somehow possible to double the size of the window when not in fullscreen mode?  So, for instance, if I was playing in **Small: 68K original mode** (640x480), it could scale up to 1280x960.

**Comment by jorio** [comment]
For now, I suggest setting the upscaling mode to "Crisp" (which is actually integer scaling), then resizing the window manually until the image is pixel-doubled.

I agree that a "windowed 2x" mode in the settings would be more convenient.

**Comment by pseudo3d** [comment]
I have a similar problem. Is it possible to have fullscreen without increasing the resolution of the original game? (Basically, an option to disable upscaling in full screen mode). [By the way, thanks for porting this, Mighty Mike/Power Pete was one of my favorites]

**Comment by jorio** [comment]
@eisnerguy1, [Mighty Mike 3.0.1](https://github.com/jorio/MightyMike/releases/tag/v3.0.1) lets you customize the size of the window. Look for "Windowed Zoom" in the video settings.

@pseudo3d, unfortunately, this is only possible in windowed mode. There is, however, an integer scaling mode for fullscreen (it's called "fullscreen, pixel perfect" in v3.0.1).

**Comment by eisnerguy1** [comment]
@jorio Awesome! Thanks! I'll give 3.0.1 a try later today. I really appreciate it 😄 👍🏻

**Comment by eisnerguy1** [comment]
Completely forgot to reply back. It works perfectly! Thank you!

**Comment by davidalanroth** [comment]
I'm on a Mac Mini with dual computer monitors. How would I use this
feature? When I do a F11, it doesn't appear to do anything. Thanks! - David

**Comment by jorio** [comment]
@davidalanroth On macOS you may have to press Command-F11. You can also switch to windowed mode via the game's settings (go to the joystick icon on the main menu, then pick Video, then Display Mode)

**Comment by davidalanroth** [comment]
Thanks! Command-F11 worked on the Mac!

I am *really* enjoying being able to play Mighty Mike again!

Best regards,

David
