### ISSUE TITLE
"S" Key to toggle sound effects doesn't work

### ISSUE THREAD

**Issue by davidalanroth** [jorio/MightyMike#20]
In the original documentation available for Mighty Mike in THE CONTROLS section the following is described:
Toggle Music On/Off      M
Toggle Effects On/Off     S

Hitting the "M" key while playing the game does work and toggles the music On and Off. However, hitting the "S" key doesn't toggle the sound effects. Instead the "S" key works as a down arrow.

Being able to turn off the music ("M") is helpful, but I always wanted to be able to toggle the sound effects as well. Or a key to completely toggle On/Off the overall sound would be helpful.

**Comment by davidalanroth** [comment]
![Mighty-Mike_The_Controls_documentation](https://github.com/jorio/MightyMike/assets/294931/9e92e564-b783-4cd6-b29e-f36bf9df907d)

**Comment by jorio** [comment]
The "S" key is collateral damage – I felt it'd be useful to let players move Mike with the WASD cluster, which is a fairly popular control scheme nowadays.

How about adding a switch to mute the sound effects in the game's Audio settings?

**Comment by davidalanroth** [comment]
I think adding a switch to mute the sound effects in the game's Audio
settings is a good idea!

Best regards,

David

**Comment by jorio** [comment]
Done - I'm not ready to make a release just yet, but you can grab a patched build [here](https://github.com/jorio/MightyMike/actions/runs/8510508269) (note: these download links will expire after a while). There's a new switch for sound effects in the audio settings.

**Comment by davidalanroth** [comment]
I tested it on the Macintosh Mac Mini (2018) running macOS 14.3.1 (23D60)
and it's perfect. Thanks!

**Comment by jorio** [comment]
You're welcome! Glad you found this useful.

**Comment by davidalanroth** [comment]
Very useful!

For those that might not be aware of the benefit of this added feature, you
can now play Mighty Mike in silence while you continue to use your
workstation for other audio purposes. Such as streaming audio.
