### ISSUE TITLE
The saved game editor?

### ISSUE THREAD

**Issue by foote-darrell** [jorio/MightyMike#3]
There was a saved game editor that worked on the old version of the game, Power Pete. [It is still downloadable](https://web.archive.org/web/20200912222619/https://www.pangeasoft.net/mightymike/support.html) on the Internet Archive. Has this been remastered as well? Or could you recreate an equivalent
 program with the same interface?

**Comment by ghost** [comment]
I've build a recreation of that editor today that works on modern macOS. I'll publish it tomorrow ☺️

**Comment by foote-darrell** [comment]
Also about the cheats, it seems there [used to be this cheat](https://web.archive.org/web/20071127143243/http://www.geocities.com/TimesSquare/Arcade/7334/) to advance to the next level. It was _Power Pete_ however, though, not _Mighty Mike._ Is this cheat been included in this version?

**Comment by macethetemplar** [comment]
.n (period n) for level end/skip

For world skips,
From the main menu, hold 2 or 3 or 4 etc and click with the mouse. This will jump you to world 2, 3 etc

**Comment by ghost** [comment]
There you go https://github.com/cyco/power-pete-cheater

**Comment by jorio** [comment]
Awesome @cyco! I added links to your tools on the README ;)
