### ISSUE TITLE
No signing and notarization

### ISSUE THREAD

**Issue by Theile** [jorio/MightyMike#8]
Bugdom has that, and it would be nice for all titles to be secured with this.

And it's really amazing work on these titles! Sorry for not mentioning that first, I was just eager to get the last little bit…

**Comment by jorio** [comment]
@Theile, [Mighty Mike 3.0.1](https://github.com/jorio/MightyMike/releases/tag/v3.0.1) is notarized now!

**Comment by Theile** [comment]
Thank you! Cool. Installomator will be updated soon.
